apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-p
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-A"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-q
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-B"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-r
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-C"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-s
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-D"
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-t
  labels:
    type: local
spec:
  storageClassName: mongodb-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb-E"
  persistentVolumeReclaimPolicy: Retain