apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-app
    maintainer: shankar-multi-container
spec:
  containers:
  - name: my-app-container
    image: busybox:latest
    env:
    - name: FIRST_NAME
      value: "Shankar"
    command: ['sh', '-c', 'echo The app is running... && sleep 3600']
  initContainers:
  - name: init-myservice
    image: busybox:latest
    command: ['sh', '-c', ]
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done']

#  Working steps as below:
# 1. The init container "init-myservice" will run first and will keep checking for the DNS resolution of "myservice.default.svc.cluster.local". 
# (its lookig for a service named "myservice" in the "default" namespace).
# If the DNS resolution fails, it will print "waiting for myservice" and wait for 2 seconds before trying again.
# Once the DNS resolution is successful, the init container will complete its execution.
# After the init container completes successfully, the main application container "my-app-container" will start running.
# The main container will print "The app is running..." and then sleep for 3600 seconds (1 hour).
# Create the above pod using the command: kubectl apply -f mc-init.yaml

#check the pod status using:
# kubectl get pods multi-container-pod
#  which shows the pending (PodInitializing) state, because its waiting for service "myservice" to be available.

# For more info : check the logs of init container using:
# kubectl logs multi-container-pod -c init-myservice

# For more info : check the logs of main container using:
# kubectl logs multi-container-pod -c my-app-container

# 2. create a deployment imperative using nginx image:
# kubectl create deploy nginx-deployment --image=nginx --port 80
#  verify the deployment using: kubectl get deployments

# 3. create a service for the above deployment to expose it within the cluster:
# kubectl expose deploy nginx-deployment --name=myservice --port=80 --target-port=80
# the name of the service is "myservice" which is being looked by init container.

# 4. Now check the pod status again using: kubectl get pods multi-container-pod 
#  which shows the running state, because now the service "myservice" is available and init container has completed successfully.

# 5. Now check the logs of init container using:
# kubectl logs multi-container-pod -c init-myservice
# which shows the successful DNS resolution of "myservice.default.svc.cluster.local".

