apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.env }}-config
data:
  DATABASE_HOST: {{ index .Values.config .Values.env "DATABASE_HOST" | quote }}
  CONTAINER_NAME: {{ index .Values.config .Values.env "CONTAINER_NAME" | quote }}
  LOG_LEVEL: {{ index .Values.config .Values.env "LOG_LEVEL" | quote }}