# Secure container configuration
apiVersion: v1
kind: Pod
metadata:
  name: secure-demo-pod-name
spec:
  securityContext:          # Pod-level security context
    runAsUser: 1000  # process id
    runAsGroup: 3000  # group id of process
    runAsNonRoot: true
    fsGroup: 2000  # file ownership group
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:       # Container-level security context
      runAsUser: 1000
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL