apiVersion: v1
kind: Pod
metadata:
  name: startup-http
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:
      httpGet:
        path: /
        port: 80
        # port: 8090 # To fail the probe, uncomment the above line and comment this line then check the status of the pod using `kubectl describe pod startup-http`
      failureThreshold: 30
      periodSeconds: 2