apiVersion: v1
kind: Pod
metadata:
  name: ambassador-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          wget -qO- localhost:8080;
          sleep 3;
        done

  - name: ambassador
    image: alpine/socat
    command:
      - "socat"
      - "TCP-LISTEN:8080,fork"
      - "TCP:backend.default.svc.cluster.local:80"