apiVersion: v1
kind: Pod
metadata:
  name: sidecar-demo
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}

  containers:
  - name: log-writer
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "$(date) - Application running" >> /var/log/app.log;
          sleep 2;
        done
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log

  - name: log-reader
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - tail -f /var/log/app.log
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log