apiVersion: v1
kind: Pod
metadata:
  name: live-tcp
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      tcpSocket:
        # port: 80
        port: 8090 # To fail the probe, uncomment the above line and comment this line then check the status of the pod using `kubectl describe pod live-tcp`
      initialDelaySeconds: 5
      periodSeconds: 5