apiVersion: v1
kind: Pod
metadata:
  name: live-exec
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "touch /tmp/healthy; sleep 3600"]
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

# This pod will be in "Running" state but will be restarted every 5 seconds until the file /tmp/healthy is created inside the container.
# You can create the file using `kubectl exec -it live-exec -- touch /tmp/healthy` and then check the status of the pod using `kubectl describe pod live-exec`.