apiVersion: v1
kind: Pod
metadata:
  name: ready-tcp
spec:
  containers:
  - name: nginx
    image: nginx
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5