apiVersion: v1
kind: Pod
metadata:
  name: startup-exec
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/started; sleep 3600
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/started
      failureThreshold: 30
      periodSeconds: 2