apiVersion: v1
kind: Pod
metadata:
  name: startup-tcp
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:
      tcpSocket:
        port: 80
      failureThreshold: 30
      periodSeconds: 2