apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: demo
spec:
  volumes:
    - name: shared-logs
      emptyDir: {}

  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html

    - name: busybox-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            echo "Hello from BusyBox at $(date)" >> /logs/index.html;
            sleep 5;
          done
      volumeMounts:
        - name: shared-logs
          mountPath: /logs
