apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    server: nginx
    maintainer: shankar
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80