apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  labels:
    app: my-clusterip-app
    maintainer: shankar-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8085
  selector:
    app: my-nginx-pod-deploy
