apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
  labels:
    app: my-clusterip-app
    maintainer: shankar-clusterip
spec:
  type: ClusterIP
  ports:
  - port: 8083 # Service port
    targetPort: 8085
  selector:
    app: my-nginx-pod-deploy

# The Service port.
  # In simple terms:
  # 👉 This is the port that the Service exposes to the outside world (or to other pods).
  # When something connects to the Service, it talks to port 8081, not directly to the pod.
  # Other pods connect to 8081
  # Kubernetes forwards traffic to container 8085