apiVersion: v1
kind: Service
metadata:
  name: my-loabalancer-service
  labels:
    app: my-loadbalancer-app
    maintainer: shankar-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8085
  selector:
    app: my-nginx-pod-deploy