apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-p
  name: redis-required
spec:
  containers:
  - image: redis
    name: redis-p
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
