apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis-p
  name: redis-prefered
spec:
  containers:
  - image: redis
    name: redis-p
  affinity: 
   nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: disktype
              operator: In
              values:
              - hdd