apiVersion: v1
kind: Config
clusters:
- name: dev-cluster
  cluster:
    server: https://127.0.0.1:6443
    certificate-authority: /path/to/ca.crt
- name: prod-cluster
  cluster:
    server: https://127.0.0.1:6445
    certificate-authority: /path/to/ca.crt

users:
- name: dev-user
  user:
    client-certificate: /path/to/client.crt
    client-key: /path/to/client.key
- name: prod-user
  user:
    client-certificate: /path/to/client.crt
    client-key: /path/to/client.key

contexts:
- name: dev-context
  context:
    cluster: dev-cluster
    user: dev-user
    namespace: default
- name: prod-context
  context:
    cluster: prod-cluster
    user: prod-user
    namespace: default

current-context: dev-context