apiVersion: v1
kind: Pod
metadata:
  name: configmap-example
spec:
  containers:
  - name: app
    image: busybox
    volumeMounts:
    - mountPath: /etc/config
      name: config-vol
  volumes:
  - name: config-vol
    configMap:
      name: app-config
      items:
      - key: log_level
        path: log_level.conf