apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-example
spec:
  containers:
  - name: app
    image: busybox
    volumeMounts:
    - mountPath: /cache
      name: cache
  volumes:
  - name: cache
    emptyDir:
      medium: Memory      # or omit for disk
      sizeLimit: 100Mi