apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: add-default-limits
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["pods"]
  mutations:
  - patchType: ApplyConfiguration
    applyConfiguration:
      expression: >
        object.spec.containers.map(c, {
          name: c.name,
          resources: has(c.resources) ?
            c.resources :
            {
              limits: {
                cpu: "500m",
                memory: "256Mi"
              }
            }
        })
